# Generated by Django 5.2.15 on 2026-06-22 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('three_wheeler', 'Three Wheeler'), ('car', 'Car'), ('van', 'Van'), ('lorry', 'Lorry')], max_length=20)),
                ('qr_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['plate_number'],
                'unique_together': {('owner', 'plate_number')},
            },
        ),
    ]
