# Generated by Django 5.2.15 on 2026-06-22 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0002_station_address_station_tank_capacities_stocklevel'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('petrol_92', 'Petrol 92'), ('petrol_95', 'Petrol 95'), ('auto_diesel', 'Auto Diesel'), ('super_diesel', 'Super Diesel')], max_length=20)),
                ('litres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivered_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='stations.station')),
            ],
            options={
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.CreateModel(
            name='DispenseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('petrol_92', 'Petrol 92'), ('petrol_95', 'Petrol 95'), ('auto_diesel', 'Auto Diesel'), ('super_diesel', 'Super Diesel')], max_length=20)),
                ('litres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('attendant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispense_logs', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispense_logs', to='stations.station')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispense_logs', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-dispensed_at'],
            },
        ),
    ]
