# Generated by Django 5.2.15 on 2026-06-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdreport',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
