# Generated by Django 5.2.15 on 2026-06-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('petrol_92', 'Petrol 92'), ('petrol_95', 'Petrol 95'), ('auto_diesel', 'Auto Diesel'), ('super_diesel', 'Super Diesel')], max_length=20)),
                ('price_per_litre', models.DecimalField(decimal_places=2, max_digits=8)),
                ('effective_from', models.DateField()),
                ('source', models.CharField(default='CPC', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'price history',
                'ordering': ['-effective_from', 'fuel_type'],
            },
        ),
    ]
