# Generated by Django 5.2.15 on 2026-06-22 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='station',
            name='tank_capacities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('petrol_92', 'Petrol 92'), ('petrol_95', 'Petrol 95'), ('auto_diesel', 'Auto Diesel'), ('super_diesel', 'Super Diesel')], max_length=20)),
                ('current_litres', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='stations.station')),
            ],
            options={
                'ordering': ['station', 'fuel_type'],
                'unique_together': {('station', 'fuel_type')},
            },
        ),
    ]
