# Generated by Django 5.2.15 on 2026-06-22 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0002_station_address_station_tank_capacities_stocklevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepletionRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('petrol_92', 'Petrol 92'), ('petrol_95', 'Petrol 95'), ('auto_diesel', 'Auto Diesel'), ('super_diesel', 'Super Diesel')], max_length=20)),
                ('horizon_hours', models.PositiveSmallIntegerField()),
                ('risk_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('risk_tier', models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], max_length=10)),
                ('estimated_hours_to_empty', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('model_name', models.CharField(default='lstm', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depletion_risks', to='stations.station')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['station', 'fuel_type', '-generated_at'], name='forecasting_station_0caffc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('petrol_92', 'Petrol 92'), ('petrol_95', 'Petrol 95'), ('auto_diesel', 'Auto Diesel'), ('super_diesel', 'Super Diesel')], max_length=20)),
                ('horizon_hours', models.PositiveSmallIntegerField()),
                ('predicted_demand_litres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('model_name', models.CharField(default='prophet', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='stations.station')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['station', 'fuel_type', '-generated_at'], name='forecasting_station_7b0fdd_idx')],
            },
        ),
    ]
