# Generated by Django 5.2.15 on 2026-06-22 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='')),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crisis_activations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activated_at'],
            },
        ),
        migrations.CreateModel(
            name='CrisisQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('three_wheeler', 'Three Wheeler'), ('car', 'Car'), ('van', 'Van'), ('lorry', 'Lorry')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol_92', 'Petrol 92'), ('petrol_95', 'Petrol 95'), ('auto_diesel', 'Auto Diesel'), ('super_diesel', 'Super Diesel')], max_length=20)),
                ('max_litres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cooldown_hours', models.PositiveSmallIntegerField(default=24)),
                ('crisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='crisis.crisismode')),
            ],
            options={
                'unique_together': {('crisis', 'vehicle_type', 'fuel_type')},
            },
        ),
    ]
